apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tomcatapp-jmx
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: tomcatapp
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
