apiVersion: v1
kind: Secret
metadata:
  name: goapp-mysql-secret
  namespace: production
type: Opaque
stringData:
  password: "Root@Percona2024!"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goapp
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: goapp
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
