apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tomcat2
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - production
  selector:
    matchLabels:
      app: tomcat2
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
