apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testapp
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testapp
          image: harbor.devops.local:7581/devops/testapp:dfb7c714
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_NAME
              value: "testapp"
            - name: APP_VERSION
              value: "2.0.0-bad"
            - name: OTEL_ENDPOINT
              value: "otel-collector.observability.svc.cluster.local:4317"
            - name: FAIL_RATE
              value: "33"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 200m
  strategy:
    canary:
      stableService: testapp-stable
      canaryService: testapp-canary
      trafficRouting:
        nginx:
          stableIngress: testapp
      analysis:
        templates:
          - templateName: success-rate
        args:
          - name: ingress-name
            value: testapp
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 80
        - pause: {duration: 30s}
