apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tomcat4
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: tomcat4
  endpoints:
    - port: jmx
      path: /metrics
      interval: 30s
